Repository MODU-TAXI/server-api, pull requests merged in 2024-05, with the labels that each got.

#47 [MS-118] SMS 서비스 사업자 변경
  build.gradle
  src/main/java/com/modutaxi/api/common/exception/errorcode/SmsErrorCode.java
  src/main/java/com/modutaxi/api/domain/mail/service/MailService.java
  src/main/java/com/modutaxi/api/domain/mail/service/MailServiceImpl.java
  src/main/java/com/modutaxi/api/domain/mail/service/MailUtil.java
  src/main/java/com/modutaxi/api/domain/member/controller/UpdateMemberController.java
  src/main/java/com/modutaxi/api/domain/sms/dto/AligoResponseDto.java
  src/main/java/com/modutaxi/api/domain/sms/service/SmsAgencyUtil.java
  src/main/java/com/modutaxi/api/domain/sms/service/SmsAgencyUtilAligo.java
  src/main/java/com/modutaxi/api/domain/sms/service/SmsAgencyUtilCoolSms.java
  src/main/java/com/modutaxi/api/domain/sms/service/SmsService.java
  src/main/java/com/modutaxi/api/domain/sms/service/SmsServiceCoolSmsImpl.java
Labels: refactor

#48 [MS-125] 모집방 엔티티 데이터 추가 및 dto 수정
  src/main/java/com/modutaxi/api/common/util/time/TimeFormatConverter.java
  src/main/java/com/modutaxi/api/domain/room/controller/RegisterRoomController.java
  src/main/java/com/modutaxi/api/domain/room/controller/UpdateRoomController.java
  src/main/java/com/modutaxi/api/domain/room/dto/RoomInternalDto.java
  src/main/java/com/modutaxi/api/domain/room/dto/RoomRequestDto.java
  src/main/java/com/modutaxi/api/domain/room/dto/RoomResponseDto.java
  src/main/java/com/modutaxi/api/domain/room/entity/Room.java
  src/main/java/com/modutaxi/api/domain/room/mapper/RoomMapper.java
  src/main/java/com/modutaxi/api/domain/room/service/GetRoomService.java
  src/main/java/com/modutaxi/api/domain/room/service/RegisterRoomService.java
  src/main/java/com/modutaxi/api/domain/room/service/UpdateRoomService.java
Labels: enhancement

#50 [MS-128] 채팅로직 FCM 연결
  src/main/java/com/modutaxi/api/common/auth/jwt/JwtTokenProvider.java
  src/main/java/com/modutaxi/api/common/config/websocket/StompHandler.java
  src/main/java/com/modutaxi/api/common/exception/errorcode/ChatErrorCode.java
  src/main/java/com/modutaxi/api/common/fcm/FcmController.java
  src/main/java/com/modutaxi/api/common/fcm/FcmService.java
  src/main/java/com/modutaxi/api/common/fcm/RedisFcmRepositoryImpl.java
  src/main/java/com/modutaxi/api/domain/chat/controller/ChatController.java
  src/main/java/com/modutaxi/api/domain/chat/repository/RedisChatRoomRepositoryImpl.java
  src/main/java/com/modutaxi/api/domain/chat/service/ChatService.java
  src/main/java/com/modutaxi/api/domain/room/controller/GetRoomController.java
  src/main/java/com/modutaxi/api/domain/room/dto/RoomResponseDto.java
  src/main/java/com/modutaxi/api/domain/room/mapper/RoomMapper.java
  src/main/java/com/modutaxi/api/domain/room/service/GetRoomService.java
  src/main/java/com/modutaxi/api/domain/room/service/RegisterRoomService.java
  src/main/java/com/modutaxi/api/domain/room/service/UpdateRoomService.java
  src/main/java/com/modutaxi/api/domain/roomwaiting/service/RoomWaitingService.java
Labels: enhancement

#53 닉네임 부여 방법 & 채팅방 인원수 관련 내부로직 변경, 대기열&참가열 조회 시 반환값 추가
  src/main/java/com/modutaxi/api/common/config/websocket/StompHandler.java
  src/main/java/com/modutaxi/api/common/exception/errorcode/RoomErrorCode.java
  src/main/java/com/modutaxi/api/domain/chat/ChatNickName.java
  src/main/java/com/modutaxi/api/domain/chat/controller/ChatController.java
  src/main/java/com/modutaxi/api/domain/chat/repository/RedisChatRoomRepositoryImpl.java
  src/main/java/com/modutaxi/api/domain/chat/service/ChatService.java
  src/main/java/com/modutaxi/api/domain/chat/service/RedisSubscriber.java
  src/main/java/com/modutaxi/api/domain/chatmessage/entity/MessageType.java
  src/main/java/com/modutaxi/api/domain/room/dto/RoomResponseDto.java
  src/main/java/com/modutaxi/api/domain/room/entity/Room.java
  src/main/java/com/modutaxi/api/domain/room/mapper/RoomMapper.java
  src/main/java/com/modutaxi/api/domain/room/service/GetRoomService.java
  src/main/java/com/modutaxi/api/domain/room/service/RegisterRoomService.java
  src/main/java/com/modutaxi/api/domain/room/service/UpdateRoomService.java
  src/main/java/com/modutaxi/api/domain/roomwaiting/controller/RoomWaitingController.java
  src/main/java/com/modutaxi/api/domain/roomwaiting/mapper/RoomWaitingMapper.java
  src/main/java/com/modutaxi/api/domain/roomwaiting/service/RoomWaitingService.java
Labels: enhancement, refactor

#55 [MS-135] 지도 정보 조회 수정
  src/main/java/com/modutaxi/api/domain/room/controller/GetRoomController.java
  src/main/java/com/modutaxi/api/domain/room/dto/RoomResponseDto.java
  src/main/java/com/modutaxi/api/domain/room/mapper/RoomMapper.java
  src/main/java/com/modutaxi/api/domain/room/service/GetRoomService.java
  src/main/java/com/modutaxi/api/domain/spot/controller/GetSpotController.java
  src/main/java/com/modutaxi/api/domain/spot/dao/SpotMysqlResponse.java
  src/main/java/com/modutaxi/api/domain/spot/dto/SpotResponseDto.java
  src/main/java/com/modutaxi/api/domain/spot/mapper/SpotResponseMapper.java
  src/main/java/com/modutaxi/api/domain/spot/repository/SpotRepository.java
  src/main/java/com/modutaxi/api/domain/spot/service/GetSpotService.java
Labels: enhancement
