Repository MODU-TAXI/server-api, pull requests merged in 2024-04, with the labels that each got.

#29 [MS-82] 거점 좋아요
  src/main/java/com/modutaxi/api/domain/likedSpot/controller/GetLikedSpotController.java
  src/main/java/com/modutaxi/api/domain/likedSpot/controller/RegisterLikedSpotController.java
  src/main/java/com/modutaxi/api/domain/likedSpot/controller/UpdateLikedSpotController.java
  src/main/java/com/modutaxi/api/domain/likedSpot/dao/LikedSpotMysqlResponse.java
  src/main/java/com/modutaxi/api/domain/likedSpot/dto/LikedSpotRequestDto.java
  src/main/java/com/modutaxi/api/domain/likedSpot/dto/LikedSpotResponseDto.java
  src/main/java/com/modutaxi/api/domain/likedSpot/entity/LikedSpot.java
  src/main/java/com/modutaxi/api/domain/likedSpot/mapper/LikedSpotResponseMapper.java
  src/main/java/com/modutaxi/api/domain/likedSpot/repository/LikedSpotRepository.java
  src/main/java/com/modutaxi/api/domain/likedSpot/service/GetLikedSpotService.java
  src/main/java/com/modutaxi/api/domain/likedSpot/service/RegisterLikedSpotService.java
  src/main/java/com/modutaxi/api/domain/likedSpot/service/UpdateLikedSpotService.java
  src/main/java/com/modutaxi/api/domain/memberspot/controller/GetMemberSpotController.java
  src/main/java/com/modutaxi/api/domain/memberspot/controller/RegisterMemberSpotController.java
  src/main/java/com/modutaxi/api/domain/memberspot/controller/UpdateMemberSpotController.java
  src/main/java/com/modutaxi/api/domain/memberspot/dto/MemberSpotRequestDto.java
  src/main/java/com/modutaxi/api/domain/memberspot/dto/MemberSpotResponseDto.java
  src/main/java/com/modutaxi/api/domain/memberspot/repository/MemberSpotRepository.java
  src/main/java/com/modutaxi/api/domain/memberspot/service/GetMemberSpotService.java
  src/main/java/com/modutaxi/api/domain/memberspot/service/RegisterMemberSpotService.java
  src/main/java/com/modutaxi/api/domain/memberspot/service/UpdateMemberSpotService.java
  src/main/java/com/modutaxi/api/domain/spot/dao/SpotMysqlResponse.java
  src/main/java/com/modutaxi/api/domain/spot/dto/SpotResponseDto.java
  src/main/java/com/modutaxi/api/domain/spot/mapper/SpotResponseMapper.java
  src/main/java/com/modutaxi/api/domain/spot/repository/SpotRepository.java
Labels: enhancement

#30 [MS-88] 반경 내 모집방 조회
  src/main/java/com/modutaxi/api/domain/room/controller/GetRoomController.java
  src/main/java/com/modutaxi/api/domain/room/dao/RoomMysqlResponse.java
  src/main/java/com/modutaxi/api/domain/room/dto/RoomInternalDto.java
  src/main/java/com/modutaxi/api/domain/room/dto/RoomResponseDto.java
  src/main/java/com/modutaxi/api/domain/room/entity/Room.java
  src/main/java/com/modutaxi/api/domain/room/mapper/RoomMapper.java
  src/main/java/com/modutaxi/api/domain/room/mapper/RoomResponseMapper.java
  src/main/java/com/modutaxi/api/domain/room/repository/RoomRepository.java
  src/main/java/com/modutaxi/api/domain/room/service/GetRoomService.java
  src/main/java/com/modutaxi/api/domain/room/service/UpdateRoomService.java
Labels: enhancement

#32 [MS-89] 거점 조회 메서드 GET 으로 변경 및 위치 dto 변경
  src/main/java/com/modutaxi/api/domain/spot/controller/GetSpotController.java
  src/main/java/com/modutaxi/api/domain/spot/controller/RegisterSpotController.java
  src/main/java/com/modutaxi/api/domain/spot/controller/UpdateSpotController.java
  src/main/java/com/modutaxi/api/domain/spot/dto/SpotRequestDto.java
  src/main/java/com/modutaxi/api/domain/spot/dto/SpotResponseDto.java
  src/main/java/com/modutaxi/api/domain/spot/mapper/SpotResponseMapper.java
Labels: refactor

#33 [MS-90] 즐겨찾기 거점 조회 반환 dto 변경
  src/main/java/com/modutaxi/api/domain/likedSpot/dto/LikedSpotResponseDto.java
  src/main/java/com/modutaxi/api/domain/likedSpot/mapper/LikedSpotResponseMapper.java
Labels: refactor

#40 [MS-65] 설문조사 API
  src/main/java/com/modutaxi/api/common/exception/errorcode/OnboardingErrorCode.java
  src/main/java/com/modutaxi/api/common/initializer/InitialApplicationListener.java
  src/main/java/com/modutaxi/api/domain/onboarding/controller/RegisterOnboardingController.java
  src/main/java/com/modutaxi/api/domain/onboarding/dto/OnboardingRequestDto.java
  src/main/java/com/modutaxi/api/domain/onboarding/entity/Onboarding.java
  src/main/java/com/modutaxi/api/domain/onboarding/entity/OnboardingAnswerList.java
  src/main/java/com/modutaxi/api/domain/onboarding/entity/OnboardingEtc.java
  src/main/java/com/modutaxi/api/domain/onboarding/entity/OnboardingQuestionList.java
  src/main/java/com/modutaxi/api/domain/onboarding/mapper/OnboardingMapper.java
  src/main/java/com/modutaxi/api/domain/onboarding/repository/OnboardingEtcRepository.java
  src/main/java/com/modutaxi/api/domain/onboarding/repository/OnboardingRepository.java
  src/main/java/com/modutaxi/api/domain/onboarding/service/RegisterOnboardingService.java
Labels: enhancement

#34 [MS-91] 전화번호 메시지 인증
  build.gradle
  src/main/java/com/modutaxi/api/common/exception/errorcode/SmsErrorCode.java
  src/main/java/com/modutaxi/api/common/util/cert/CertificationCodeUtil.java
  src/main/java/com/modutaxi/api/domain/mail/service/MailService.java
  src/main/java/com/modutaxi/api/domain/mail/service/MailServiceImpl.java
  src/main/java/com/modutaxi/api/domain/mail/service/MailUtil.java
  src/main/java/com/modutaxi/api/domain/member/controller/UpdateMemberController.java
  src/main/java/com/modutaxi/api/domain/member/dto/MemberRequestDto.java
  src/main/java/com/modutaxi/api/domain/member/dto/MemberResponseDto.java
  src/main/java/com/modutaxi/api/domain/member/repository/RedisSnsIdRepository.java
  src/main/java/com/modutaxi/api/domain/member/repository/RedisSnsIdRepositoryImpl.java
  src/main/java/com/modutaxi/api/domain/member/service/UpdateMemberService.java
  src/main/java/com/modutaxi/api/domain/sms/dao/SmsCertCodeEntity.java
  src/main/java/com/modutaxi/api/domain/sms/repository/RedisSmsCertificationCodeRepository.java
  src/main/java/com/modutaxi/api/domain/sms/repository/RedisSmsCertificationCodeRepositoryImpl.java
  src/main/java/com/modutaxi/api/domain/sms/service/SmsService.java
  src/main/java/com/modutaxi/api/domain/sms/service/SmsServiceCoolSmsImpl.java
Labels: enhancement

#42 [MS-107] 전화 인증 시 동일한 조건으로 재전송 시 무조건 에러를 반환 하던 오류 수정
  src/main/java/com/modutaxi/api/domain/sms/service/SmsServiceCoolSmsImpl.java
Labels: bug

#43 [MS-106] 거점 관련 기능 수정
  src/main/java/com/modutaxi/api/domain/spot/controller/GetSpotController.java
  src/main/java/com/modutaxi/api/domain/spot/repository/SpotRepository.java
  src/main/java/com/modutaxi/api/domain/spot/service/GetSpotService.java
Labels: bug, enhancement

#44 [MS-108] 반경 내 모집방 검색 시 특정 거점 목적지 필터링 추가
  src/main/java/com/modutaxi/api/domain/room/controller/GetRoomController.java
  src/main/java/com/modutaxi/api/domain/room/repository/RoomRepository.java
  src/main/java/com/modutaxi/api/domain/room/service/GetRoomService.java
Labels: enhancement
