Repository MODU-TAXI/server-api, pull requests merged in 2024-06, with the labels that each got.

#57 [MS-147] 도착지 지도 조회 최소개수 조회 방식으로 변경
  src/main/java/com/modutaxi/api/domain/spot/controller/GetSpotController.java
  src/main/java/com/modutaxi/api/domain/spot/dao/SpotMysqlResponse.java
  src/main/java/com/modutaxi/api/domain/spot/dto/SpotResponseDto.java
  src/main/java/com/modutaxi/api/domain/spot/repository/SpotRepository.java
  src/main/java/com/modutaxi/api/domain/spot/service/GetSpotService.java
Labels: enhancement

#60 [MS-146] 신고하기 API 수정 사항 반영
  src/main/java/com/modutaxi/api/common/slack/SlackService.java
  src/main/java/com/modutaxi/api/domain/member/controller/RegisterMemberController.java
  src/main/java/com/modutaxi/api/domain/member/controller/UpdateMemberController.java
  src/main/java/com/modutaxi/api/domain/member/dto/MemberRequestDto.java
  src/main/java/com/modutaxi/api/domain/member/dto/MemberResponseDto.java
  src/main/java/com/modutaxi/api/domain/member/entity/Member.java
  src/main/java/com/modutaxi/api/domain/member/mapper/MemberMapper.java
  src/main/java/com/modutaxi/api/domain/member/service/RegisterMemberService.java
  src/main/java/com/modutaxi/api/domain/member/service/UpdateMemberService.java
  src/main/java/com/modutaxi/api/domain/report/controller/RegisterReportController.java
  src/main/java/com/modutaxi/api/domain/report/dto/ReportRequestDto.java
  src/main/java/com/modutaxi/api/domain/report/entity/Report.java
  src/main/java/com/modutaxi/api/domain/report/mapper/ReportMapper.java
  src/main/java/com/modutaxi/api/domain/report/repository/ReportRepository.java
  src/main/java/com/modutaxi/api/domain/report/service/RegisterReportService.java
  src/main/java/com/modutaxi/api/domain/room/controller/RegisterRoomController.java
  src/main/java/com/modutaxi/api/domain/room/service/RegisterRoomService.java
  src/main/java/com/modutaxi/api/domain/roomwaiting/controller/RoomWaitingController.java
  src/main/java/com/modutaxi/api/domain/roomwaiting/mapper/RoomWaitingMapper.java
  src/main/java/com/modutaxi/api/domain/roomwaiting/service/RoomWaitingService.java
Labels: enhancement

#59 [MS-149] dynamic scheduler 적용
  src/main/java/com/modutaxi/api/common/config/SchedulerConfig.java
  src/main/java/com/modutaxi/api/common/config/websocket/StompHandler.java
  src/main/java/com/modutaxi/api/common/exception/errorcode/StompErrorCode.java
  src/main/java/com/modutaxi/api/domain/chat/controller/ChatController.java
  src/main/java/com/modutaxi/api/domain/chat/service/ChatSchedulerService.java
  src/main/java/com/modutaxi/api/domain/chat/service/ChatService.java
  src/main/java/com/modutaxi/api/domain/chat/service/RedisSubscriber.java
  src/main/java/com/modutaxi/api/domain/chatmessage/entity/ChatMessage.java
  src/main/java/com/modutaxi/api/domain/chatmessage/mapper/ChatMessageMapper.java
  src/main/java/com/modutaxi/api/domain/room/dto/RoomResponseDto.java
  src/main/java/com/modutaxi/api/domain/room/mapper/RoomMapper.java
  src/main/java/com/modutaxi/api/domain/room/service/GetRoomService.java
  src/main/java/com/modutaxi/api/domain/room/service/RegisterRoomService.java
  src/main/java/com/modutaxi/api/domain/room/service/UpdateRoomService.java
  src/main/java/com/modutaxi/api/domain/roomwaiting/service/RoomWaitingService.java
Labels: enhancement

#61 [MS-152] Refactor: socket error handling 고도화
  src/main/java/com/modutaxi/api/common/config/websocket/StompExceptionHandler.java
  src/main/java/com/modutaxi/api/common/config/websocket/StompHandler.java
  src/main/java/com/modutaxi/api/common/exception/BaseException.java
  src/main/java/com/modutaxi/api/common/exception/ControllerAdvice.java
  src/main/java/com/modutaxi/api/common/exception/SocketErrorCode.java
  src/main/java/com/modutaxi/api/common/exception/StompException.java
  src/main/java/com/modutaxi/api/common/exception/errorcode/StompErrorCode.java
  src/main/java/com/modutaxi/api/domain/chat/service/RedisSubscriber.java
Labels: refactor

#62 [MS-134] 프로필 업데이트 버그 수정
  src/main/java/com/modutaxi/api/common/util/validator/NicknameValidator.java
  src/main/java/com/modutaxi/api/domain/member/dto/MemberRequestDto.java
  src/main/java/com/modutaxi/api/domain/member/entity/Member.java
  src/main/java/com/modutaxi/api/domain/member/service/UpdateMemberService.java
Labels: bug

#63 [MS-153] Feat: 지도, 리스트 통합 조회 API
  src/main/java/com/modutaxi/api/common/exception/errorcode/RoomErrorCode.java
  src/main/java/com/modutaxi/api/domain/room/controller/GetRoomController.java
  src/main/java/com/modutaxi/api/domain/room/dao/RoomMysqlResponse.java
  src/main/java/com/modutaxi/api/domain/room/dto/RoomResponseDto.java
  src/main/java/com/modutaxi/api/domain/room/mapper/RoomMapper.java
  src/main/java/com/modutaxi/api/domain/room/repository/RoomRepositoryDSL.java
  src/main/java/com/modutaxi/api/domain/room/repository/RoomRepositoryDSLImpl.java
  src/main/java/com/modutaxi/api/domain/room/service/GetRoomService.java
Labels: enhancement

#64 [MS-155] 거점 조회 시 거점을 모두 포함하는 양 끝점 반환
  src/main/java/com/modutaxi/api/domain/spot/dto/SpotResponseDto.java
  src/main/java/com/modutaxi/api/domain/spot/service/GetSpotService.java
Labels: enhancement

#68 [MS-158] 경로 조회시 경로 최대 최소 지점 반환
  src/main/java/com/modutaxi/api/domain/room/dto/RoomResponseDto.java
  src/main/java/com/modutaxi/api/domain/room/mapper/RoomMapper.java
Labels: enhancement

#70 [MS-148] 객체 업로드 시 현재 프로파일 호출 방법 수정
  src/main/java/com/modutaxi/api/common/s3/S3Service.java
Labels: bug

#74 [MS-45] 로그인 로직 변경
  src/main/java/com/modutaxi/api/domain/member/controller/RegisterMemberController.java
  src/main/java/com/modutaxi/api/domain/member/dto/MemberResponseDto.java
  src/main/java/com/modutaxi/api/domain/member/service/RegisterMemberService.java
Labels: enhancement

#76 [MS-168] room delete, re request scheduling & FCM refactor
  src/main/java/com/modutaxi/api/common/fcm/FcmController.java
  src/main/java/com/modutaxi/api/common/fcm/FcmService.java
  src/main/java/com/modutaxi/api/domain/chatmessage/entity/MessageType.java
  src/main/java/com/modutaxi/api/domain/participant/repository/ParticipantRepository.java
  src/main/java/com/modutaxi/api/domain/scheduledmessage/service/ScheduledMessageService.java
Labels: enhancement

#77 [MS-21] 애플 로그인, 탈퇴
  build.gradle
  src/main/java/com/modutaxi/api/ApiApplication.java
  src/main/java/com/modutaxi/api/common/auth/oauth/SocialLoginService.java
  src/main/java/com/modutaxi/api/common/auth/oauth/apple/client/AppleOauthClient.java
  src/main/java/com/modutaxi/api/common/auth/oauth/apple/controller/AppleController.java
  src/main/java/com/modutaxi/api/common/auth/oauth/apple/dto/AppleAuthServerRequest.java
  src/main/java/com/modutaxi/api/common/auth/oauth/apple/dto/AppleAuthServerResponse.java
  src/main/java/com/modutaxi/api/common/auth/oauth/apple/dto/AppleIdTokenPayload.java
  src/main/java/com/modutaxi/api/common/auth/oauth/apple/dto/AppleRequest.java
  src/main/java/com/modutaxi/api/common/auth/oauth/apple/service/AppleService.java
  src/main/java/com/modutaxi/api/common/auth/oauth/apple/vo/AppleOauthProperties.java
  src/main/java/com/modutaxi/api/common/config/SecurityConfig.java
  src/main/java/com/modutaxi/api/common/exception/errorcode/AuthErrorCode.java
  src/main/java/com/modutaxi/api/domain/member/repository/MemberRepository.java
  src/main/java/com/modutaxi/api/domain/member/service/GetMemberService.java
  src/main/java/com/modutaxi/api/domain/member/service/RegisterMemberService.java
Labels: enhancement

#78 [MS-172] 택시팟 목표인원 수 반환값 조정
  src/main/java/com/modutaxi/api/domain/room/entity/Room.java
  src/main/java/com/modutaxi/api/domain/room/mapper/RoomMapper.java
Labels: enhancement

#80 [MS-143] 알림 API 요청 사항 반영
  src/main/java/com/modutaxi/api/domain/alarm/controller/GetAlarmController.java
  src/main/java/com/modutaxi/api/domain/alarm/dto/AlarmResponseDto.java
  src/main/java/com/modutaxi/api/domain/alarm/entity/Alarm.java
  src/main/java/com/modutaxi/api/domain/alarm/mapper/AlarmMapper.java
  src/main/java/com/modutaxi/api/domain/alarm/repository/AlarmRepository.java
  src/main/java/com/modutaxi/api/domain/alarm/service/GetAlarmService.java
Labels: enhancement

#79 [MS-119] FCM DB 저장 로직 추가
  src/main/java/com/modutaxi/api/common/fcm/FcmService.java
  src/main/java/com/modutaxi/api/domain/member/entity/Member.java
  src/main/java/com/modutaxi/api/domain/member/service/RegisterMemberService.java
Labels: enhancement, refactor

#82 [MS-145] Fix: Alarm 엔티티 필드 네이밍 변경
  src/main/java/com/modutaxi/api/domain/alarm/dto/AlarmResponseDto.java
  src/main/java/com/modutaxi/api/domain/alarm/entity/Alarm.java
  src/main/java/com/modutaxi/api/domain/alarm/mapper/AlarmMapper.java
  src/main/java/com/modutaxi/api/domain/alarm/repository/AlarmRepository.java
Labels: bug

#84 [MS-119] Fix: 회원가입 버그 수정
  src/main/java/com/modutaxi/api/domain/member/service/RegisterMemberService.java
Labels: bug

#83 [MS-174] Jwt용 sms 인증 엔드포인트 생성 및 휴대폰 번호 중복사용 방지 로직 추가
  src/main/java/com/modutaxi/api/common/config/SecurityConfig.java
  src/main/java/com/modutaxi/api/common/exception/errorcode/SmsErrorCode.java
  src/main/java/com/modutaxi/api/domain/member/controller/UpdateMemberController.java
  src/main/java/com/modutaxi/api/domain/member/dto/MemberRequestDto.java
  src/main/java/com/modutaxi/api/domain/member/repository/MemberRepository.java
  src/main/java/com/modutaxi/api/domain/member/service/UpdateMemberService.java
  src/main/java/com/modutaxi/api/domain/sms/service/SmsService.java
Labels: enhancement
